### ISSUE TITLE
LuaJIT but not Lua segfaults when code from noiseutils is run

### ISSUE THREAD

**Issue by CrackedP0t** [CrackedP0t/LuaNoise#4]
For example, this will segfault:

```
noise = require("noise")
noisemap = noise.NoiseMap()
```

**Comment by padicao2010** [comment]
Luajit and Fedora 23.
tutorial_2 OK
tutorial_3 segments at renderer:Render()
tutorial_4 segments at renderer:SetLightContrast(3)
tutorial_5 segments at quiting the program
tutorial_6 segments at quiting the program
tutorial_7 segments at quiting the program
tutorial_8 segments at renderer:Render()

**Comment by CrackedP0t** [comment]
@padicao2010 How'd you figure this out?

**Comment by padicao2010** [comment]
@CrackedP0t Easy. I've added some print statements in the source codes, in order to find out where the program exit abnormally.

**Comment by CrackedP0t** [comment]
Fixed in  2d77a94. The GC metamethod wasn't returning a value, and apparently Lua was OK with it but LuaJIT wasn't.
